<a href="https://colab.research.google.com/github/iMike-505/Tratamiento-de-Datos/blob/main/02Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Conceptos básicos de *Numpy*.
[*Numpy*](http://www.numpy.org/) es un paquete que contiene una biblioteca de recursos especializados en realizar operaciones optimizadas en arreglos de datos.

El proyecto *Numpy* cuenta con una extensa documentación, la cual está disponible en https://docs.scipy.org/doc/numpy/.


In [ ]:
# Instalacion del paquete
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
# Importamos el paquete numpy
import numpy as np

In [ ]:
arreglo = np.array((1,2,3))
arreglo

array([1, 2, 3])

In [ ]:
type(arreglo)

numpy.ndarray

In [ ]:
for i in arreglo:
  print('valor: {}, tipo: {}'. format(i, type(i)))

valor: 1, tipo: <class 'numpy.int64'>
valor: 2, tipo: <class 'numpy.int64'>
valor: 3, tipo: <class 'numpy.int64'>


In [ ]:
arreglo = np.array((1,2,3.5))
print(arreglo)
print(type(arreglo))
for i in arreglo:
  print('valor: {}, tipo: {}'. format(i, type(i)))

[1.  2.  3.5]
<class 'numpy.ndarray'>
valor: 1.0, tipo: <class 'numpy.float64'>
valor: 2.0, tipo: <class 'numpy.float64'>
valor: 3.5, tipo: <class 'numpy.float64'>


In [ ]:
arreglo = np.array(['d', 3, (12, 6, True)], dtype = object)
for i in arreglo:
  print('valor: {}, tipo: {}'. format(i, type(i)))

valor: d, tipo: <class 'str'>
valor: 3, tipo: <class 'int'>
valor: (12, 6, True), tipo: <class 'tuple'>


### El atributo ```shape```.

Los arreglos cuentan con el atributo ```shape```, el cual describe el número de elementos que contiene cada dimensión del arreglo.

El valor de ```shape``` es un objeto tipo tuple que contiene una sucesión de números.

```
(<n1>, <n2>, <n3> ... <nm>)
```

* Donde ```<n1>``` corresponde al número de elementos en la primera dimensión,  ```<n2>``` corresponde al número de elementos en la segunda dimensión y así sucesivamente hasta ```<nm>``` , la cual corrersponde al número de elementos de la dimensión ```m```.

In [ ]:
# Arreglo unidimensional
arreglo = np.array((1,2,3))
print(arreglo.ndim) #Numero de dimensiones
print(arreglo.shape) #Elementos en cada dimensión
print(arreglo.size) #Numero total de elementos del arreglo

1
(3,)
3


In [ ]:
# Arreglo bidimensional
arreglo = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(arreglo.ndim) #Numero de dimensiones
print(arreglo.shape) #Elementos en cada dimensión
print(arreglo.size) #Numero total de elementos del arreglo

2
(2, 3)
6


In [ ]:
# Arreglo tridimensional
arreglo = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print(arreglo.ndim) #Numero de dimensiones
print(arreglo.shape) #Elementos en cada dimensión
print(arreglo.size) #Numero total de elementos del arreglo

3
(2, 2, 2)
8


In [ ]:
# Tipo por default
np.array(((1, 2), (3, 4))).dtype

dtype('int64')

In [ ]:
np.array(((-1, 2), (3, 4)), dtype = np.uint8)


array([[255,   2],
       [  3,   4]], dtype=uint8)

In [ ]:
np.array(((-1, 2), (3, 4)), dtype = np.uint64)

array([[18446744073709551615,                    2],
       [                   3,                    4]], dtype=uint64)

In [ ]:
# Complejo
complejo = np.array([[25.6j, 11.24],
                     [-21.890-15702174.43j, 0]])
print(complejo)
print(complejo.dtype)

[[  0.  +2.56000000e+01j  11.24+0.00000000e+00j]
 [-21.89-1.57021744e+07j   0.  +0.00000000e+00j]]
complex128


In [ ]:
#Arreglo booleano
np.array(((1,'Hola'), (False, 0)), dtype = np.bool_)

array([[ True,  True],
       [False, False]])

In [ ]:
#Tipo cadena
np.array((['Hugo', 'Paco'],['Luis Ignacio', 'Donald']))

array([['Hugo', 'Paco'],
       ['Luis Ignacio', 'Donald']], dtype='<U12')