<a href="https://colab.research.google.com/github/iMike-505/Tratamiento-de-Datos/blob/main/03_NumpyOperationsipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
m1 = np.array([[1,2,3],
              [10,11,12],
              [-5,-8,-14]])
print(m1)
print(m1.shape)

[[  1   2   3]
 [ 10  11  12]
 [ -5  -8 -14]]
(3, 3)


In [3]:
#Las operaciones aritmeticas se aplican a todos los elementos de la matriz
m1 * 200

array([[  200,   400,   600],
       [ 2000,  2200,  2400],
       [-1000, -1600, -2800]])

In [5]:
#Al aplicar la operación a un elemento
m1[1] + 15

array([25, 26, 27])

In [6]:
m1 / 5.45

array([[ 0.18348624,  0.36697248,  0.55045872],
       [ 1.83486239,  2.01834862,  2.20183486],
       [-0.91743119, -1.46788991, -2.56880734]])

In [7]:
#Usar operadores lógicos por broadcasting
m1 > 1

array([[False,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [9]:
m2 = np.array([1, 2, 3])
m3 = np.array([[2], [4], [6]])

print(m2)
print(m2.shape)

print(m3)
print(m3.shape)

print(m1)
print(m1.shape)

[1 2 3]
(3,)
[[2]
 [4]
 [6]]
(3, 1)
[[  1   2   3]
 [ 10  11  12]
 [ -5  -8 -14]]
(3, 3)


In [10]:
m1 * m2

array([[  1,   4,   9],
       [ 10,  22,  36],
       [ -5, -16, -42]])

In [11]:
m1 / m3

array([[ 0.5       ,  1.        ,  1.5       ],
       [ 2.5       ,  2.75      ,  3.        ],
       [-0.83333333, -1.33333333, -2.33333333]])

In [12]:
m4 = m1 + 20
m4

array([[21, 22, 23],
       [30, 31, 32],
       [15, 12,  6]])

In [13]:
m1 * m4

array([[ 21,  44,  69],
       [300, 341, 384],
       [-75, -96, -84]])

In [17]:
#Generar arreglos con valores aleatorios
np.random.rand(2, 2, 2)

array([[[0.55692386, 0.1385443 ],
        [0.35529161, 0.60246337]],

       [[0.31855952, 0.42682764],
        [0.45231493, 0.11209058]]])

In [43]:
#randint genera valores enteros aleatorios entre un rango
np.random.randint(1, 4, (2, 2, 2))

array([[[1, 1],
        [2, 2]],

       [[3, 3],
        [1, 2]]])

In [19]:
np.random.randint(0, 256, (3, 2, 4))

array([[[138, 131,  72, 110],
        [214,  96,  99, 151]],

       [[ 83,  45, 116, 145],
        [  5, 187, 236, 101]],

       [[  9, 177, 218, 198],
        [127,  35, 127,  70]]])

In [53]:
numeros = np.array([[2.43, -3, 48.9999, -5.61],
                   [np.inf, -np.inf, np.inf, np.inf],
                   [np.nan, 17.78, 12, 22]])
numeros

array([[ 2.43  , -3.    , 48.9999, -5.61  ],
       [    inf,    -inf,     inf,     inf],
       [    nan, 17.78  , 12.    , 22.    ]])

In [54]:
#Funciones de valor
print(np.abs(numeros))
print(np.floor(numeros))
print(np.ceil(numeros))
print(np.round(numeros))

[[ 2.43    3.     48.9999  5.61  ]
 [    inf     inf     inf     inf]
 [    nan 17.78   12.     22.    ]]
[[  2.  -3.  48.  -6.]
 [ inf -inf  inf  inf]
 [ nan  17.  12.  22.]]
[[  3.  -3.  49.  -5.]
 [ inf -inf  inf  inf]
 [ nan  18.  12.  22.]]
[[  2.  -3.  49.  -6.]
 [ inf -inf  inf  inf]
 [ nan  18.  12.  22.]]


## Funciones de valor
* ```np.abs()```
* ```np.around()```
* ```np.ceil()```
* ```np.exp()```
* ```np.exp2()```
* ```np.fabs()```
* ```np.fix()```
* ```np.floor()```
* ```np.log()```
* ```np.log10()```
* ```np.log1p()```
* ```np.log2()```
* ```np.logaddexp()```
* ```np.logaddexp2()```
* ```np.round()```


In [55]:
#Funciones de evaluación de arreglos
print(np.isfinite(numeros))
print(np.isnan(numeros))
print(np.isreal(numeros))
print(np.isscalar(numeros))

[[ True  True  True  True]
 [False False False False]
 [False  True  True  True]]
[[False False False False]
 [False False False False]
 [ True False False False]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
False


## Funciones estadísticas.

* ```np.amax()```
* ```np amin()```
* ```np.argmax()```
* ```np.argmin()```
* ```np.average()```
* ```np.correlate()```
* ```np.corrcoef()```
* ```np.count_nonzero()```
* ```np.cov()```
* ```np.cumprod()```
* ```np.cumsum()```
* ```np.histogram()```
* ```np.histogram2d()```
* ```np.histogram_bin_edges()```
* ```np.histogramdd()```
* ```np.max()```
* ```np.mean()```
* ```np.median()```
* ```np.min()```
* ```np.nanargmax()```
* ```np.nanargmin()```
* ```np.nancumprod()```
* ```np.nancumsum()```
* ```np.nanmax()```
* ```np.nanmean()```
* ```np.nanmedian()```
* ```np.nanmin()```
* ```np.nanpercentile()```
* ```np.nanquantile()```
* ```np.nanstd()```
* ```np.nansum()```
* ```np.nanvar()```
* ```np.percentile()```
* ```np.quantile()```
* ```np.std()```
* ```np.var()```


In [58]:
numeros = np.random.randint(0, 256, (3, 2, 4))
numeros

array([[[ 69, 189, 180, 129],
        [ 30, 107, 153, 134]],

       [[167,  87,  85, 176],
        [225, 102, 250,  35]],

       [[ 26,  43, 210, 196],
        [212,  44,  71,  15]]])

In [61]:
print(np.max(numeros))
print(np.mean(numeros))
print(np.min(numeros))
print(np.median(numeros))

250
122.29166666666667
15
118.0


In [62]:
print(np.nanmax(numeros))
print(np.nanmin(numeros))
print(np.nanmean(numeros))
print(np.nanmedian(numeros))

250
15
122.29166666666667
118.0


In [63]:
np.histogram(numeros)

(array([4, 2, 3, 3, 1, 2, 2, 3, 3, 1]),
 array([ 15. ,  38.5,  62. ,  85.5, 109. , 132.5, 156. , 179.5, 203. ,
        226.5, 250. ]))

In [64]:
#Copia y ordenamiento
numeros1 = numeros #Alias de un arreglo
numeros1 = np.copy(numeros) #Copia del arreglo
numeros1

array([[[ 69, 189, 180, 129],
        [ 30, 107, 153, 134]],

       [[167,  87,  85, 176],
        [225, 102, 250,  35]],

       [[ 26,  43, 210, 196],
        [212,  44,  71,  15]]])

In [65]:
numeros1.sort() #Sort sirve para ordenar
numeros1

array([[[ 69, 129, 180, 189],
        [ 30, 107, 134, 153]],

       [[ 85,  87, 167, 176],
        [ 35, 102, 225, 250]],

       [[ 26,  43, 196, 210],
        [ 15,  44,  71, 212]]])

In [67]:
numeros1.sort(axis=2) #axis ordena un eje en particular
numeros1

array([[[ 30, 107, 134, 153],
        [ 69, 129, 180, 189]],

       [[ 35,  87, 167, 176],
        [ 85, 102, 225, 250]],

       [[ 15,  43,  71, 210],
        [ 26,  44, 196, 212]]])

In [68]:
a = np.array([1,2,3])
b = np.array([(1,2,3), (4,5,6)])
print(a)
print(b)
print(np.add(a, b))

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[2 4 6]
 [5 7 9]]


In [70]:
#suma tota de los elementos
b.sum()

21

In [71]:
#Raiz cuadrada
np.sqrt(b)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [72]:
#Crear un arreglo con los resultados de una comparación lógica
c = b <= 4
c

array([[ True,  True,  True],
       [ True, False, False]])